# Generated by Django 4.0.4 on 2022-05-16 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chamado',
            fields=[
                ('id_chamado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data_chamado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
