# Generated by Django 4.0.4 on 2022-05-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='horas',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
